#Rachel Ate It
donut_post="Duck Donuts is a one of a kind donut shop! Every single one is made to order, you can customize the frosting, drizzle, and toppings! My favorite seasonal falvors are Blueberry Pancake, Strawberry Shortcake, and Cinnamon Bun. Some crazy flavors include Maple Bacon- where they cover the donut with maple icing and add pieces of fresh bacon on the top. You can even add salted caramel drizzle on top if you're feeling extra daring. The crazy part is you can even get breakfast sandwiches made on these insanely delicious donuts. I would highly recommend going to a Duck Donuts shop if there's one in your area!"
crepe_post="The Crepe Shop in Chicago is an amazing place to go if you enjoy exotic tasting crepes! This place finds a way to combine flavors together inside a crepe in a way I've never tasted. The lemon curd crepes were my absolute favorite but I'm definitely going back to try some others. Their fresh-brewed local coffee is also a great complement to their crepes! Savory or sweet, you will not be disappointed in any crepe you order from here, so if you're in the Chicago area definitely stop by!"
mac_post="The Leaning Pear is a delicious restaurant with hill country-inspired cuisine. Originally starting in Texas this place migrated up to Chicago and we are so happy they're here! The bacon mac'n cheese was the most delicious I've ever tasted. I can't wait to go back and try their fried brussel sprouts and wood-fired pizza. If you're a Texan visiting Chicago please come try this restaurant, you will not be disappointed."
toast_post="This French bakery is making the brunch scene in Chicago amazing! Speaking from my time in Paris this place does it right. Their French fusion taste is so unique, and accompanied by a twist that takes your experience to the next level, I highly suggest trying this bakery. Combined with their delicious coffee menu this place is amazing for a leisurely morning brunch or a nice afternoon lunch date. The avocado toast was my brunch of choice but I'm definitely going back to try more food off the menu."
bucatini_post="This pasta was so delicious and I got it from a small little place in Chicago named Lula Cafe. I've never tried pasta for brunch but this was one of the best decisions I've ever made. The way they combined the brown butter, feta, and garlic made this pasta taste better than I ever could have imagined. Their upscale menu has many other options on it as well like Baked French Feta and a Savory Ricotta Hand Pie. Brunch is a sacred meal and this little cafe in Chicago does it so well."
burger_post="Who would've thought this burger is vegan! It tasted just like real meat but so much healthier! Burgerlords is the only burger joint I've ever been to that has all vegan/vegetarian options, and it's insane how well they do it. This place originally started in LA and has made its way to Chicago. With wild options like tofu nuggets and vegan breakfast burritos you're sure to find something that suits your fancy and is healthier than ordinary non-vegan items."
pasta_post="This pasta place called the Sfizio Family was a litle hole in the wall family-owned restaurant that I found in Paris while I was there for school. It was so good and all their pasta was made from scratch. If I'm ever back in that part of the world I will do my best to track down this little pasta place and have some more."
fries_post="The Bandit is such a diverse place to go with foods from all over the world. Their takes on so many common dishes are so refreshing and exilerating to try. The Bulgogi fries had Bulgogi braised short ribs, 5-year aged cheddar, and 1-year aged kimchi! There are so many other delicious dishes to try and you can combine your eating experience with the neighborhood bar vibe they also have. They also have different special events happening weekly- ranging from Friday Brunch to Happy Hour to Football Gamedays.If you're looking for a fun place to hang out with amazing food The Bandit is the place for you!"

b1=Blog.create(name: "Donuts", restaurant: "Duck Donuts", description: "Nothing tastes better than a fresh hot donut with melty gooey frosting topped with drizzles and sprinkles", post: donut_post, image: "/image/Donuts.jpeg")
b2=Blog.create(name: "Lemon Curd Crepe", restaurant: "The Crepe Shop", description: "I died and went to heaven after a bite of this lemon curd crepe 😍 and then washed it down with a vanilla bean latte made w oatly oat milk 🤤", post: crepe_post, image: "/image/Tacos.png")
b3=Blog.create(name: "Bacon Mac n Cheese", restaurant: "The Leaning Pear", description: "I had the option to eat salad...still went for the Bacon Mac’n’cheese! 🤷🏼‍♀️", post: mac_post, image: "/image/MacNCheese.jpeg")
b4=Blog.create(name: "Avocado Toast", restaurant: "Maison Marcel Chicago", description: "Avocado toast and drumroll....Purple Cauliflower Grits!!! It 👏🏻 was 👏🏻 AMAZING!", post: toast_post, image: "/image/AvoToast.jpeg")
b5=Blog.create(name: "Bucatini", restaurant: "Lula Cafe", description: "Pasta for brunch is ALWAYS a good idea. Especially when it’s bucatini in browned butter with feta and garlic 🤤", post: bucatini_post, image: "/image/Bucatini.jpeg")
b6=Blog.create(name: "Classic Cheeseburger", restaurant: "Burgerlords", description: "Literally nothing is better than a fat juicy cheeseburger, hot fries, and a thick milkshake. NOTHING. and Burgerlords does it the best.", post: burger_post, image: "/image/Burger.jpeg")
b7=Blog.create(name: "Scratch Pasta", restaurant: "Sfizio Family", description: "This little scratch pasta place in Paris was such a hole in the wall! We found it less than 2 blocks away from school. So fresh so delish, and under 10€", post: pasta_post, image: "/image/FrenchPasta.jpeg")
b8=Blog.create(name: "Bulgogi Fries", restaurant: "Bandit", description: "Kimchi + Bulgogi fries & mozz sticks?? How could I say no? (Hint...I couldn’t. 😂)", post: fries_post, image: "/image/BulgogiFries.jpeg")

#Rachel Made It
g1=BakedGood.create(name: "Vanilla Cake", price: 50, image: "/image/BdayCake.jpeg", description: "Nothing is better than a birthday cake! This one has FOUR whole vanilla beans in the sponge, Osmo Salt salted Swiss meringue buttercream, and Maldon Salt salted whipped caramel filling 🤯🤯 HIGHLY recommend trying out this vanilla cake recipe by Philip Khoury 🤤")
g2=BakedGood.create(name: "Pumpkin Cookies", price: 15, image: "/image/PumpkinCookies.jpeg", description: "Anyday is a good day for my favorite pumpkin cookie recipe! Pumpkin is a year-round dessert, not just fall!")
g3=BakedGood.create(name: "Red Velvet Cake", price: 55, image: "/image/RedVelvet.jpeg", description: "If you don’t like Red Velvet Cake, then I don’t like you. Especially when it’s made with Nielsen Massey real vanilla bean paste in a whipped cream cream cheese frosting 🍰")
g4=BakedGood.create(name: "Fruit Pizza", price: 30, image: "/image/FruitPizza.jpeg", description: "Perfect for July 4th (or any time of year for all you fruit lovers). Enjoy this fruit pizza 😍 extra berries please!")
g5=BakedGood.create(name: "Tiramisu", price: 75, image: "/image/Tiramisu.jpeg", description: "I like my tiramisu extra juicy with lots of cream 🤤 still trying to figure out how Belgioioso Cheese makes their mascarpone cheese so perfectly creamy 🥰")
g6=BakedGood.create(name: "Vegan Brownies", price: 20, image: "/image/Brownies.jpeg", description: "I’m not vegan...but these brownies are! Tbh...I’ve always been a fan of using real butter/eggs and have never baked vegan. But these brownies are SO good, I may have to rethink things! Thanks to The Big Man's World for the recipe!")
g7=BakedGood.create(name: "Caramel Macarons", price: 32, image: "/image/CaramelMacaroons.jpeg", description: "Name a better combo than flaky sea salt and caramel...go ahead, I’ll wait! 😉 these crispy on the outside chewy on the inside macarons with a rich, salty caramel filling are DIVINE!")
g8=BakedGood.create(name: "Pumpkin Cake", price: 17, image: "/image/PumpkinCake.jpeg", description: "Hopping on the Pumpkin Train Express! All aboard! 🚂 call it pumpkin cake, pumpkin bars, or what I prefer- breakfast! This cake is amazing..but what pushes it over the limit is the whipped cream cream cheese frosting made with Nielsen Massey vanilla bean paste 😍🤤")
g9=BakedGood.create(name: "Madeleines", price: 22, image: "/image/Madeleines.jpeg", description: "I’m in love with these Madeleines 🥰 and adding a little lemon zest to the batter and pairing with homemade raspberry jelly is the bomb 💣 I’m holding on to all the last drops of summer that I can with these little pillows of love 🌞")
g10=BakedGood.create(name: "Chocolate Chip Cookies", price: 40, image: "/image/Cookie.jpeg", description: "Everyone says they have the best recipe for chocolate chip cookies, and I am no different!🍪 I just can’t get over the crinkly tops and chewy insides 🤤 I have a little secret...these are made with cannabis butter 🍁Shhhhhh!!")
g11=BakedGood.create(name: "Lemon Curd Tarte", price: 45, image: "/image/LemonTart.jpeg", description: "Tarte au citron is way underrated in my opinion. I used to hate lemon! I think (know) I was crazy back then... or maybe I was just missing this silky lemon curd with the perfect balance of sour and sweet 🤷🏼‍♀️")
g12=BakedGood.create(name: "Lemon Curd Macarons", price: 20, image: "/image/LemonCurd.png", description: "I bet your Easter would be better with these Lemon Curd Macarons 😉 🍋 🐰")
g13=BakedGood.create(name: "Birthday Cake Macarons", price: 20, image: "/image/BDayMacarons.png", description: "(Happy) Birthday Cake Macarons!! Who would you order these for?? 🎂😍")